<template>
  <page-view title="Pathology AI Model" logo="https://gw.alipayobjects.com/zos/rmsportal/nxkuOJlFJuAUhzlMTCEe.png">
    <a-table class="pathology-model-container" :columns="columns" :data-source="data">
      <a slot="link" slot-scope="text, record" @click="redirectToRecord(record.file_path, 'tcoa')">{{ text }}</a>
      <a slot="operation" slot-scope="text" @click="showModal">Prediction</a>
      <span slot="status" slot-scope="text">
        <a-tag color="#87d068" v-if="text === 'Success'">
          {{ text }}
        </a-tag>
        <a-tag color="#f50" v-if="text === 'Error'">
          {{ text }}
        </a-tag>
        <a-tag color="#108ee9" v-if="text === 'Running'">
          {{ text }}
        </a-tag>
      </span>
      <template v-slot:expandedRowRender="record">
        <a-table :columns="innerColumns" :data-source="innerData" :pagination="false" class="inner-table">
          <span slot="status" slot-scope="text">
            <a-tag color="#87d068" v-if="text === 'Success'">
              {{ text }}
            </a-tag>
            <a-tag color="#f50" v-if="text === 'Error'">
              {{ text }}
            </a-tag>
            <a-tag color="#108ee9" v-if="text === 'Running'">
              {{ text }}
            </a-tag>
          </span>
          <span slot="operation" slot-scope="text" class="table-operation">
            <a @click="redirectToRecord(record.file_path, 'tcoa')">View</a>
          </span>
        </a-table>
      </template>
    </a-table>
    <a-modal
      class="prediction-modal"
      title="Choose Model(s)"
      :width="450"
      :visible="visible"
      @ok="prediction"
      @cancel="hideModal"
    >
      <a-checkbox-group :options="modelOptions" />
    </a-modal>
  </page-view>
</template>

<script>
import { PageView } from '@/layouts'

const columns = [
  {
    title: 'File Name',
    dataIndex: 'file_name',
    key: 'file_name',
    align: 'left',
    scopedSlots: { customRender: 'link' }
  },
  {
    title: 'Patient ID',
    dataIndex: 'patient_id',
    key: 'patient_id',
    align: 'center'
  },
  {
    title: 'Disease Type',
    dataIndex: 'disease_type',
    key: 'disease_type',
    align: 'center'
  },
  {
    title: 'Primary Site',
    dataIndex: 'primary_site',
    key: 'primary_site',
    align: 'center'
  },
  {
    title: 'Data Format',
    dataIndex: 'data_format',
    key: 'data_format',
    align: 'center'
  },
  {
    title: 'Data Category',
    dataIndex: 'data_category',
    key: 'data_category',
    align: 'center'
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
    align: 'center',
    scopedSlots: { customRender: 'status' }
  },
  {
    title: 'Action',
    key: 'operation',
    scopedSlots: { customRender: 'operation' },
    align: 'center'
  }
]

const innerColumns = [
  { title: 'Model Name', dataIndex: 'modelName', key: 'modelName' },
  { title: 'Description', align: 'center', dataIndex: 'description', key: 'description' },
  { title: 'Status', align: 'center', dataIndex: 'status', key: 'status', scopedSlots: { customRender: 'status' } },
  { title: 'Report', key: 'action', scopedSlots: { customRender: 'operation' } }
]

export default {
  components: {
    PageView
  },
  data() {
    return {
      data: [
        {
          status: 'Success',
          a_260_a_280_ratio: '',
          aa_change: '',
          adapter_name: '',
          adapter_sequence: '',
          adverse_event: '',
          adverse_event_grade: '',
          age_at_diagnosis: '63',
          age_at_index: '63',
          age_at_onset: '',
          age_is_obfuscated: '',
          aids_risk_factors: '',
          ajcc_clinical_m: '',
          ajcc_clinical_n: 'N0',
          ajcc_clinical_stage: '',
          ajcc_clinical_t: 'T2',
          ajcc_pathologic_m: '',
          ajcc_pathologic_n: '',
          ajcc_pathologic_stage: '',
          ajcc_pathologic_t: '',
          ajcc_staging_system_edition: '',
          alcohol_days_per_week: '',
          alcohol_drinks_per_day: '',
          alcohol_history: '',
          alcohol_intensity: '',
          alcohol_type: '',
          analyte__amount: '',
          analyte__analyte_type: '',
          analyte__analyte_type_id: '',
          analyte__concentration: '',
          analyte__submitter_id: '',
          analyte_quantity: '',
          analyte_volume: '',
          anaplasia_present: '',
          anaplasia_present_type: '',
          ann_arbor_b_symptoms: '',
          ann_arbor_clinical_stage: '',
          ann_arbor_extranodal_involvement: '',
          ann_arbor_pathologic_stage: '',
          anthracyclines: 'TRUE',
          antigen: '',
          asbestos_exposure: '',
          ascat_acf: '0.42',
          ascat_ploidy: '2.939498835',
          barretts_esophagus_goblet_cells_present: '',
          base_caller_name: '',
          base_caller_version: '',
          bc_diagnosis__submitter_id: '',
          best_overall_response: '',
          biospecimen_anatomic_site: '',
          biospecimen_laterality: '',
          biospecimen_type: '',
          biospecimen_volume: '',
          blood_test_normal_range_lower: '',
          blood_test_normal_range_upper: '',
          body_surface_area: '',
          bone_marrow_malignant_cells: '',
          brca_12_mut: 'FALSE',
          brca_1_mut: 'FALSE',
          brca_2_mut: 'FALSE',
          breslow_thickness: '',
          burkitt_lymphoma_clinical_variant: '',
          catalog_reference: '',
          cause_of_death: '',
          cause_of_death_source: '',
          cause_of_response: '',
          cd_4_count: '',
          cdc_hiv_risk_factors: '',
          cell_count: '',
          chemo_concurrent_to_radiation: '',
          chemotherapy: 'TRUE',
          chemotherapy_other_regimen: 'FALSE',
          chemotherapy_regimen_unknown: 'FALSE',
          child_pugh_classification: '',
          chipseq_target: '',
          chromosome: '',
          cigarettes_per_day: '',
          circumferential_resection_margin: '',
          classification_of_tumor: '',
          clonality: '',
          cna_subtype: 'Low_CIN',
          coal_dust_exposure: '',
          cog_liver_stage: '',
          cog_neuroblastoma_risk_group: '',
          cog_renal_stage: '',
          cog_rhabdomyosarcoma_risk_group: '',
          columnar_mucosa_present: '',
          comorbidity: '',
          comorbidity_method_of_diagnosis: '',
          composition: '',
          consent_type: '',
          contralateral_supraclavicular_ln_metastasis: 'FALSE',
          copy_number: '',
          country_of_residence_at_enrollment: '',
          creation_datetime: '',
          current_weight: '',
          cytoband: '',
          data_category: 'Tissue Slide',
          data_format: 'NDPI',
          data_type: 'Pathology Image',
          datafile_id: 'FUSCCTNBC001.ndpi',
          days_to_adverse_event: '',
          days_to_best_overall_response: '',
          days_to_birth: '',
          days_to_collection: '',
          days_to_comorbidity: '',
          days_to_consent: '',
          days_to_death: '',
          days_to_diagnosis: '',
          days_to_follow_up: '',
          days_to_imaging: '',
          days_to_last_follow_up: '',
          days_to_last_known_disease_status: '',
          days_to_lost_to_followup: '',
          days_to_progression: '',
          days_to_progression_free: '',
          days_to_sample_procurement: '',
          days_to_sequencing: '',
          days_to_treatment_end: '',
          days_to_treatment_start: '',
          demographic__submitter_id: '',
          diabetes_treatment_type: '',
          diagnosis__days_to_recurrence: '1549',
          diagnosis__mitotic_count: '',
          diagnosis__progression_or_recurrence: '',
          diagnosis__submitter_id: '',
          diagnosis_pathologically_confirmed: '',
          disease_response: '',
          disease_type: 'TNBC',
          distance_normal_to_tumor: '',
          distributor_reference: '',
          dlco_ref_predictive_percent: '',
          dysplasia_degree: '',
          dysplasia_type: '',
          ecog_performance_status: '',
          eln_risk_classification: '',
          enneking_msts_grade: '',
          enneking_msts_metastasis: '',
          enneking_msts_stage: '',
          enneking_msts_tumor_site: '',
          environmental_tobacco_smoke_exposure: '',
          er_ihc_score: 'Negative',
          erbb_2_fish: 'NA',
          erbb_2_ihc_score: '0',
          esophageal_columnar_dysplasia_degree: '',
          esophageal_columnar_metaplasia_present: '',
          ethnicity: '',
          evidence_of_recurrence_type: '',
          exon: '',
          experiment_name: '',
          experimental_strategy: 'Pathology',
          exposure__bmi: '',
          exposure__height: '',
          exposure__submitter_id: '',
          exposure__weight: '',
          exposure_duration: '',
          exposure_type: '',
          family_history__submitter_id: '',
          fev_1_fvc_post_bronch_percent: '',
          fev_1_fvc_pre_bronch_percent: '',
          fev_1_ref_post_bronch_percent: '',
          fev_1_ref_pre_bronch_percent: '',
          fibrosis: 'NA',
          figo_stage: '',
          figo_staging_edition_year: '',
          file__submitter_id: '',
          file_name: 'FUSCCTNBC001.ndpi',
          file_path: '/mnt/pgx_src_data_pool_3/clinico-omics/FUSCCTNBC_RNAseq_Shao_2019/FUSCCTNBC001.ndpi',
          file_size: '1572864',
          first_symptom_prior_to_diagnosis: '',
          flow_cell_barcode: '',
          follow_up__bmi: '',
          follow_up__height: '',
          follow_up__progression_or_recurrence: '',
          follow_up__submitter_id: '',
          follow_up__weight: '',
          fraction_genome_altered: '0.1729',
          fragment_maximum_length: '',
          fragment_mean_length: '',
          fragment_minimum_length: '',
          fragment_standard_deviation_length: '',
          freezing_method: '',
          gastric_esophageal_junction_involvement: '',
          gender: 'famale',
          gene_symbol: '',
          gleason_grade_group: '',
          gleason_grade_tertiary: '',
          gleason_patterns_percent: '',
          goblet_cells_columnar_mucosa_present: '',
          greatest_tumor_dimension: '',
          gross_tumor_weight: '',
          growth_rate: '',
          haart_treatment_indicator: '',
          hepatitis_sustained_virological_response: '',
          histology: 'MC',
          histology_extended: 'NA',
          histone_family: '',
          histone_variant: '',
          hiv_viral_load: '',
          hormonal_contraceptive_type: '',
          hormonal_contraceptive_use: '',
          hormone_replacement_therapy_type: '',
          hpv_positive_type: '',
          hrd: '20.43776806',
          hta_id: 'NA',
          hysterectomy_margins_involved: '',
          hysterectomy_type: '',
          i_cluster_subtype: 'iC6',
          i_ti_ls: '10',
          icd_10_code: '',
          igcccg_stage: '',
          imaging_result: '',
          imaging_type: '',
          immunosuppressive_treatment_type: '',
          includes_spike_ins: '',
          index_date: '2011/11/1',
          initial_disease_status: '',
          initial_weight: '',
          inpc_grade: '',
          inpc_histologic_group: '',
          inrg_stage: '',
          inss_stage: '',
          instrument_model: '',
          intermediate_dimension: '',
          international_prognostic_index: '',
          intrinsic_subtype: 'Basal',
          intron: '',
          irs_group: '',
          irs_stage: '',
          is_paired_end: '1',
          ishak_fibrosis_score: '',
          iss_stage: '',
          karnofsky_performance_status: '',
          kbase_identifier: '1',
          ki_67: '30',
          laboratory_test: '',
          lane_number: '',
          largest_extrapelvic_peritoneal_focus: '',
          last_known_disease_status: '',
          laterality: '',
          lc_3_b_zs: 'NA',
          library_name: 'Lib_FUSCCTNBC001',
          library_preparation_kit_catalog_number: '',
          library_preparation_kit_name: '',
          library_preparation_kit_vendor: '',
          library_preparation_kit_version: '',
          library_selection: 'cDNA',
          library_strand: '',
          library_strategy: 'RNA-Seq',
          ln_examed: '18',
          ln_positive: '0',
          loci_abnormal_count: '111',
          loci_count: '',
          locus: '',
          loh: '13',
          longest_dimension: '',
          lost_to_followup: '',
          ls_tm: '6.437768063',
          lymph_node_involved_site: '',
          lymph_node_involvement: '',
          lymph_nodes_positive: '',
          lymph_nodes_tested: '',
          lymphatic_invasion_present: '',
          m_rna_subtype: 'IM',
          margin_distance: '',
          margin_status: '',
          margins_involved_site: '',
          marijuana_use_per_week: '',
          masaoka_stage: '',
          md_5_sum: '',
          medulloblastoma_molecular_classification: '',
          menopause: 'TRUE',
          menopause_status: '',
          metaplasia_present: '',
          metastasis_at_diagnosis: 'FALSE',
          metastasis_at_diagnosis_site: '',
          method_of_diagnosis: '',
          method_of_sample_procurement: '',
          micropapillary_features: '',
          mismatch_repair_mutation: '',
          mitosis_karyorrhexis_index: '',
          mitotic_total_area: '',
          molecular_analysis_method: '',
          molecular_consequence: '',
          molecular_test__mitotic_count: '',
          molecular_test__submitter_id: '',
          morphologic_architectural_pattern: '',
          morphology: '',
          multiplex_barcode: '',
          mutation_subtype: 'HRD',
          nadir_cd_4_count: '',
          necrosis: 'NA',
          non_nodal_regional_disease: '',
          non_nodal_tumor_deposits: '',
          normal_tumor_genotype_snp_match: '',
          number_expect_cells: '',
          number_of_cycles: '',
          number_proliferating_cells: '',
          occupation_duration_years: '',
          oct_embedded: '',
          onco_scan_array: 'YES',
          ovarian_specimen_status: '',
          ovarian_surface_involvement: '',
          pack_years_smoked: '',
          paclitaxel: 'FALSE',
          pancreatitis_onset_year: '',
          papillary_renal_cell_type: '',
          passage_count: '',
          pathogenicity: '',
          pathology_detail__submitter_id: '',
          pathology_report_uuid: '',
          patient_id: 'FUSCCTNBC001',
          percent_eosinophil_infiltration: '',
          percent_follicular_component: '',
          percent_granulocyte_infiltration: '',
          percent_inflam_infiltration: '',
          percent_lymphocyte_infiltration: '',
          percent_monocyte_infiltration: '',
          percent_necrosis: '',
          percent_neutrophil_infiltration: '',
          percent_normal_cells: '',
          percent_rhabdoid_features: '',
          percent_sarcomatoid_features: '',
          percent_stromal_cells: '',
          percent_tumor_cells: '',
          percent_tumor_invasion: '',
          percent_tumor_nuclei: '',
          perineural_invasion: 'FALSE',
          perineural_invasion_present: '',
          peripancreatic_lymph_nodes_positive: '',
          peripancreatic_lymph_nodes_tested: '',
          peritoneal_fluid_cytological_status: '',
          platins: 'FALSE',
          ploidy: '',
          portion__is_ffpe: '',
          portion__submitter_id: '',
          portion__weight: '',
          portion_number: '',
          pr_ihc_score: 'Negative',
          pregnancy_outcome: '',
          pregnant_at_diagnosis: '',
          premature_at_birth: '',
          preservation_method: '',
          primary_diagnosis: '',
          primary_gleason_grade: '',
          primary_site: 'Breast',
          prior_malignancy: '',
          prior_treatment: '',
          procedures_performed: '',
          progression_or_recurrence_anatomic_site: '',
          progression_or_recurrence_type: '',
          project__submitter_id: 'PGX',
          project_id: 'FUSCCTNBC',
          prostatic_chips_positive_count: '',
          prostatic_chips_total_count: '',
          prostatic_involvement_percent: '',
          race: '',
          radiotherapy: 'FALSE',
          radon_exposure: '',
          read_group__platform: 'ILLUMINA',
          read_group__submitter_id: '',
          read_group_id: 'FUSCCTNBC001_ForRNAseq.TumorTissue',
          read_group_name: '',
          read_length: '',
          reason_treatment_ended: '',
          recist_targeted_regions_number: '',
          recist_targeted_regions_sum: '',
          reflux_treatment_type: '',
          regimen_or_line_of_therapy: '',
          relationship_age_at_diagnosis: '',
          relationship_gender: '',
          relationship_primary_diagnosis: '',
          relationship_type: '',
          relative_with_cancer_history: '',
          relatives_with_cancer_history_count: '',
          residual_disease: '',
          respirable_crystalline_silica_exposure: '',
          rfs_status: 'DiseaseFree',
          rfs_time_months: '51.6',
          ribosomal_rna_28_s_16_s_ratio: '',
          rin: '',
          risk_factor: '',
          risk_factor_treatment: '',
          s_ti_ls: '10',
          sample__is_ffpe: '',
          sample__submitter_id: '',
          sample_id: 'FUSCCTNBC001_ForRNAseq.TumorTissue',
          sample_type: '',
          sample_type_id: '',
          satellite_nodule_present: '',
          scan_tracer_used: '',
          secondary_gleason_grade: '',
          secondhand_smoke_as_child: '',
          section_location: '',
          sequencing_center: 'FUDAN UNIVERSITY SHANGHAI CANCER CENTER',
          sequencing_date: '2019-03-13T00:00:00Z',
          shortest_dimension: '',
          single_cell_library: '',
          site_of_resection_or_biopsy: '',
          sites_of_involvement: '',
          size_selection_range: '',
          smokeless_tobacco_quit_age: '',
          smoking_frequency: '',
          snf_subtype: 'SC2',
          spectrophotometer_method: '',
          spike_ins_concentration: '',
          spike_ins_fasta: '',
          supratentorial_localization: '',
          surgery: 'MRM',
          synchronous_malignancy: '',
          target_capture_kit: '',
          target_capture_kit_catalog_number: '',
          target_capture_kit_name: '',
          target_capture_kit_target_region: '',
          target_capture_kit_vendor: '',
          target_capture_kit_version: '',
          telomeric_ai: '1',
          test_analyte_type: '',
          test_result: '',
          test_units: '',
          test_value: '',
          therapeutic_agents: '',
          time_between_clamping_and_freezing: '',
          time_between_excision_and_freezing: '',
          time_between_waking_and_first_smoke: '',
          tissue_collection_type: '',
          tissue_microarray_coordinates: '',
          tissue_or_organ_of_origin: '',
          tissue_type: 'TumorTissue',
          to_trim_adapter_sequence: '',
          tobacco_smoking_onset_year: '',
          tobacco_smoking_quit_year: '',
          tobacco_smoking_status: '',
          tobacco_use_per_day: '',
          transcript: '',
          transglottic_extension: '',
          treatment__submitter_id: '',
          treatment_anatomic_site: '',
          treatment_arm: '',
          treatment_dose: '',
          treatment_dose_units: '',
          treatment_effect: '',
          treatment_effect_indicator: '',
          treatment_frequency: '',
          treatment_intent_type: '',
          treatment_or_therapy: '',
          treatment_outcome: '',
          treatment_type: '',
          tumor_code: '',
          tumor_code_id: '',
          tumor_confined_to_organ_of_origin: '',
          tumor_depth: '',
          tumor_descriptor: '',
          tumor_focality: '',
          tumor_grade: 'NA',
          tumor_largest_dimension_diameter: '4',
          tumor_regression_grade: '',
          tumor_stage: '',
          type_of_smoke_exposure: '',
          type_of_tobacco_used: '',
          variant_origin: '',
          variant_type: '',
          vascular_invasion_present: '',
          vascular_invasion_type: '',
          viral_hepatitis_serologies: '',
          vital_status: '',
          weeks_gestation_at_birth: '',
          weiss_assessment_score: '',
          well_number: '',
          who_cns_grade: '',
          who_nte_grade: '',
          wilms_tumor_histologic_subtype: '',
          year_of_birth: '',
          year_of_death: '',
          year_of_diagnosis: '',
          years_smoked: '',
          zygosity: ''
        },
        {
          status: 'Success',
          a_260_a_280_ratio: '',
          aa_change: '',
          adapter_name: '',
          adapter_sequence: '',
          adverse_event: '',
          adverse_event_grade: '',
          age_at_diagnosis: '63',
          age_at_index: '63',
          age_at_onset: '',
          age_is_obfuscated: '',
          aids_risk_factors: '',
          ajcc_clinical_m: '',
          ajcc_clinical_n: 'N0',
          ajcc_clinical_stage: '',
          ajcc_clinical_t: 'T2',
          ajcc_pathologic_m: '',
          ajcc_pathologic_n: '',
          ajcc_pathologic_stage: '',
          ajcc_pathologic_t: '',
          ajcc_staging_system_edition: '',
          alcohol_days_per_week: '',
          alcohol_drinks_per_day: '',
          alcohol_history: '',
          alcohol_intensity: '',
          alcohol_type: '',
          analyte__amount: '',
          analyte__analyte_type: '',
          analyte__analyte_type_id: '',
          analyte__concentration: '',
          analyte__submitter_id: '',
          analyte_quantity: '',
          analyte_volume: '',
          anaplasia_present: '',
          anaplasia_present_type: '',
          ann_arbor_b_symptoms: '',
          ann_arbor_clinical_stage: '',
          ann_arbor_extranodal_involvement: '',
          ann_arbor_pathologic_stage: '',
          anthracyclines: 'TRUE',
          antigen: '',
          asbestos_exposure: '',
          ascat_acf: '0.42',
          ascat_ploidy: '2.939498835',
          barretts_esophagus_goblet_cells_present: '',
          base_caller_name: '',
          base_caller_version: '',
          bc_diagnosis__submitter_id: '',
          best_overall_response: '',
          biospecimen_anatomic_site: '',
          biospecimen_laterality: '',
          biospecimen_type: '',
          biospecimen_volume: '',
          blood_test_normal_range_lower: '',
          blood_test_normal_range_upper: '',
          body_surface_area: '',
          bone_marrow_malignant_cells: '',
          brca_12_mut: 'FALSE',
          brca_1_mut: 'FALSE',
          brca_2_mut: 'FALSE',
          breslow_thickness: '',
          burkitt_lymphoma_clinical_variant: '',
          catalog_reference: '',
          cause_of_death: '',
          cause_of_death_source: '',
          cause_of_response: '',
          cd_4_count: '',
          cdc_hiv_risk_factors: '',
          cell_count: '',
          chemo_concurrent_to_radiation: '',
          chemotherapy: 'TRUE',
          chemotherapy_other_regimen: 'FALSE',
          chemotherapy_regimen_unknown: 'FALSE',
          child_pugh_classification: '',
          chipseq_target: '',
          chromosome: '',
          cigarettes_per_day: '',
          circumferential_resection_margin: '',
          classification_of_tumor: '',
          clonality: '',
          cna_subtype: 'Low_CIN',
          coal_dust_exposure: '',
          cog_liver_stage: '',
          cog_neuroblastoma_risk_group: '',
          cog_renal_stage: '',
          cog_rhabdomyosarcoma_risk_group: '',
          columnar_mucosa_present: '',
          comorbidity: '',
          comorbidity_method_of_diagnosis: '',
          composition: '',
          consent_type: '',
          contralateral_supraclavicular_ln_metastasis: 'FALSE',
          copy_number: '',
          country_of_residence_at_enrollment: '',
          creation_datetime: '',
          current_weight: '',
          cytoband: '',
          data_category: 'Tissue Slide',
          data_format: 'NDPI',
          data_type: 'Pathology Image',
          datafile_id: 'FUSCCTNBC005.ndpi',
          days_to_adverse_event: '',
          days_to_best_overall_response: '',
          days_to_birth: '',
          days_to_collection: '',
          days_to_comorbidity: '',
          days_to_consent: '',
          days_to_death: '',
          days_to_diagnosis: '',
          days_to_follow_up: '',
          days_to_imaging: '',
          days_to_last_follow_up: '',
          days_to_last_known_disease_status: '',
          days_to_lost_to_followup: '',
          days_to_progression: '',
          days_to_progression_free: '',
          days_to_sample_procurement: '',
          days_to_sequencing: '',
          days_to_treatment_end: '',
          days_to_treatment_start: '',
          demographic__submitter_id: '',
          diabetes_treatment_type: '',
          diagnosis__days_to_recurrence: '1549',
          diagnosis__mitotic_count: '',
          diagnosis__progression_or_recurrence: '',
          diagnosis__submitter_id: '',
          diagnosis_pathologically_confirmed: '',
          disease_response: '',
          disease_type: 'TNBC',
          distance_normal_to_tumor: '',
          distributor_reference: '',
          dlco_ref_predictive_percent: '',
          dysplasia_degree: '',
          dysplasia_type: '',
          ecog_performance_status: '',
          eln_risk_classification: '',
          enneking_msts_grade: '',
          enneking_msts_metastasis: '',
          enneking_msts_stage: '',
          enneking_msts_tumor_site: '',
          environmental_tobacco_smoke_exposure: '',
          er_ihc_score: 'Negative',
          erbb_2_fish: 'NA',
          erbb_2_ihc_score: '0',
          esophageal_columnar_dysplasia_degree: '',
          esophageal_columnar_metaplasia_present: '',
          ethnicity: '',
          evidence_of_recurrence_type: '',
          exon: '',
          experiment_name: '',
          experimental_strategy: 'Pathology',
          exposure__bmi: '',
          exposure__height: '',
          exposure__submitter_id: '',
          exposure__weight: '',
          exposure_duration: '',
          exposure_type: '',
          family_history__submitter_id: '',
          fev_1_fvc_post_bronch_percent: '',
          fev_1_fvc_pre_bronch_percent: '',
          fev_1_ref_post_bronch_percent: '',
          fev_1_ref_pre_bronch_percent: '',
          fibrosis: 'NA',
          figo_stage: '',
          figo_staging_edition_year: '',
          file__submitter_id: '',
          file_name: 'FUSCCTNBC005.ndpi',
          file_path: '/mnt/pgx_src_data_pool_3/clinico-omics/FUSCCTNBC_RNAseq_Shao_2019/FUSCCTNBC005.ndpi',
          file_size: '1572864',
          first_symptom_prior_to_diagnosis: '',
          flow_cell_barcode: '',
          follow_up__bmi: '',
          follow_up__height: '',
          follow_up__progression_or_recurrence: '',
          follow_up__submitter_id: '',
          follow_up__weight: '',
          fraction_genome_altered: '0.1729',
          fragment_maximum_length: '',
          fragment_mean_length: '',
          fragment_minimum_length: '',
          fragment_standard_deviation_length: '',
          freezing_method: '',
          gastric_esophageal_junction_involvement: '',
          gender: 'famale',
          gene_symbol: '',
          gleason_grade_group: '',
          gleason_grade_tertiary: '',
          gleason_patterns_percent: '',
          goblet_cells_columnar_mucosa_present: '',
          greatest_tumor_dimension: '',
          gross_tumor_weight: '',
          growth_rate: '',
          haart_treatment_indicator: '',
          hepatitis_sustained_virological_response: '',
          histology: 'MC',
          histology_extended: 'NA',
          histone_family: '',
          histone_variant: '',
          hiv_viral_load: '',
          hormonal_contraceptive_type: '',
          hormonal_contraceptive_use: '',
          hormone_replacement_therapy_type: '',
          hpv_positive_type: '',
          hrd: '20.43776806',
          hta_id: 'NA',
          hysterectomy_margins_involved: '',
          hysterectomy_type: '',
          i_cluster_subtype: 'iC6',
          i_ti_ls: '10',
          icd_10_code: '',
          igcccg_stage: '',
          imaging_result: '',
          imaging_type: '',
          immunosuppressive_treatment_type: '',
          includes_spike_ins: '',
          index_date: '2011/11/1',
          initial_disease_status: '',
          initial_weight: '',
          inpc_grade: '',
          inpc_histologic_group: '',
          inrg_stage: '',
          inss_stage: '',
          instrument_model: '',
          intermediate_dimension: '',
          international_prognostic_index: '',
          intrinsic_subtype: 'Basal',
          intron: '',
          irs_group: '',
          irs_stage: '',
          is_paired_end: '1',
          ishak_fibrosis_score: '',
          iss_stage: '',
          karnofsky_performance_status: '',
          kbase_identifier: '1',
          ki_67: '30',
          laboratory_test: '',
          lane_number: '',
          largest_extrapelvic_peritoneal_focus: '',
          last_known_disease_status: '',
          laterality: '',
          lc_3_b_zs: 'NA',
          library_name: 'Lib_FUSCCTNBC005',
          library_preparation_kit_catalog_number: '',
          library_preparation_kit_name: '',
          library_preparation_kit_vendor: '',
          library_preparation_kit_version: '',
          library_selection: 'cDNA',
          library_strand: '',
          library_strategy: 'RNA-Seq',
          ln_examed: '18',
          ln_positive: '0',
          loci_abnormal_count: '111',
          loci_count: '',
          locus: '',
          loh: '13',
          longest_dimension: '',
          lost_to_followup: '',
          ls_tm: '6.437768063',
          lymph_node_involved_site: '',
          lymph_node_involvement: '',
          lymph_nodes_positive: '',
          lymph_nodes_tested: '',
          lymphatic_invasion_present: '',
          m_rna_subtype: 'IM',
          margin_distance: '',
          margin_status: '',
          margins_involved_site: '',
          marijuana_use_per_week: '',
          masaoka_stage: '',
          md_5_sum: '',
          medulloblastoma_molecular_classification: '',
          menopause: 'TRUE',
          menopause_status: '',
          metaplasia_present: '',
          metastasis_at_diagnosis: 'FALSE',
          metastasis_at_diagnosis_site: '',
          method_of_diagnosis: '',
          method_of_sample_procurement: '',
          micropapillary_features: '',
          mismatch_repair_mutation: '',
          mitosis_karyorrhexis_index: '',
          mitotic_total_area: '',
          molecular_analysis_method: '',
          molecular_consequence: '',
          molecular_test__mitotic_count: '',
          molecular_test__submitter_id: '',
          morphologic_architectural_pattern: '',
          morphology: '',
          multiplex_barcode: '',
          mutation_subtype: 'HRD',
          nadir_cd_4_count: '',
          necrosis: 'NA',
          non_nodal_regional_disease: '',
          non_nodal_tumor_deposits: '',
          normal_tumor_genotype_snp_match: '',
          number_expect_cells: '',
          number_of_cycles: '',
          number_proliferating_cells: '',
          occupation_duration_years: '',
          oct_embedded: '',
          onco_scan_array: 'YES',
          ovarian_specimen_status: '',
          ovarian_surface_involvement: '',
          pack_years_smoked: '',
          paclitaxel: 'FALSE',
          pancreatitis_onset_year: '',
          papillary_renal_cell_type: '',
          passage_count: '',
          pathogenicity: '',
          pathology_detail__submitter_id: '',
          pathology_report_uuid: '',
          patient_id: 'FUSCCTNBC005',
          percent_eosinophil_infiltration: '',
          percent_follicular_component: '',
          percent_granulocyte_infiltration: '',
          percent_inflam_infiltration: '',
          percent_lymphocyte_infiltration: '',
          percent_monocyte_infiltration: '',
          percent_necrosis: '',
          percent_neutrophil_infiltration: '',
          percent_normal_cells: '',
          percent_rhabdoid_features: '',
          percent_sarcomatoid_features: '',
          percent_stromal_cells: '',
          percent_tumor_cells: '',
          percent_tumor_invasion: '',
          percent_tumor_nuclei: '',
          perineural_invasion: 'FALSE',
          perineural_invasion_present: '',
          peripancreatic_lymph_nodes_positive: '',
          peripancreatic_lymph_nodes_tested: '',
          peritoneal_fluid_cytological_status: '',
          platins: 'FALSE',
          ploidy: '',
          portion__is_ffpe: '',
          portion__submitter_id: '',
          portion__weight: '',
          portion_number: '',
          pr_ihc_score: 'Negative',
          pregnancy_outcome: '',
          pregnant_at_diagnosis: '',
          premature_at_birth: '',
          preservation_method: '',
          primary_diagnosis: '',
          primary_gleason_grade: '',
          primary_site: 'Breast',
          prior_malignancy: '',
          prior_treatment: '',
          procedures_performed: '',
          progression_or_recurrence_anatomic_site: '',
          progression_or_recurrence_type: '',
          project__submitter_id: 'PGX',
          project_id: 'FUSCCTNBC',
          prostatic_chips_positive_count: '',
          prostatic_chips_total_count: '',
          prostatic_involvement_percent: '',
          race: '',
          radiotherapy: 'FALSE',
          radon_exposure: '',
          read_group__platform: 'ILLUMINA',
          read_group__submitter_id: '',
          read_group_id: 'FUSCCTNBC005_ForRNAseq.TumorTissue',
          read_group_name: '',
          read_length: '',
          reason_treatment_ended: '',
          recist_targeted_regions_number: '',
          recist_targeted_regions_sum: '',
          reflux_treatment_type: '',
          regimen_or_line_of_therapy: '',
          relationship_age_at_diagnosis: '',
          relationship_gender: '',
          relationship_primary_diagnosis: '',
          relationship_type: '',
          relative_with_cancer_history: '',
          relatives_with_cancer_history_count: '',
          residual_disease: '',
          respirable_crystalline_silica_exposure: '',
          rfs_status: 'DiseaseFree',
          rfs_time_months: '51.6',
          ribosomal_rna_28_s_16_s_ratio: '',
          rin: '',
          risk_factor: '',
          risk_factor_treatment: '',
          s_ti_ls: '10',
          sample__is_ffpe: '',
          sample__submitter_id: '',
          sample_id: 'FUSCCTNBC005_ForRNAseq.TumorTissue',
          sample_type: '',
          sample_type_id: '',
          satellite_nodule_present: '',
          scan_tracer_used: '',
          secondary_gleason_grade: '',
          secondhand_smoke_as_child: '',
          section_location: '',
          sequencing_center: 'FUDAN UNIVERSITY SHANGHAI CANCER CENTER',
          sequencing_date: '2019-03-13T00:00:00Z',
          shortest_dimension: '',
          single_cell_library: '',
          site_of_resection_or_biopsy: '',
          sites_of_involvement: '',
          size_selection_range: '',
          smokeless_tobacco_quit_age: '',
          smoking_frequency: '',
          snf_subtype: 'SC2',
          spectrophotometer_method: '',
          spike_ins_concentration: '',
          spike_ins_fasta: '',
          supratentorial_localization: '',
          surgery: 'MRM',
          synchronous_malignancy: '',
          target_capture_kit: '',
          target_capture_kit_catalog_number: '',
          target_capture_kit_name: '',
          target_capture_kit_target_region: '',
          target_capture_kit_vendor: '',
          target_capture_kit_version: '',
          telomeric_ai: '1',
          test_analyte_type: '',
          test_result: '',
          test_units: '',
          test_value: '',
          therapeutic_agents: '',
          time_between_clamping_and_freezing: '',
          time_between_excision_and_freezing: '',
          time_between_waking_and_first_smoke: '',
          tissue_collection_type: '',
          tissue_microarray_coordinates: '',
          tissue_or_organ_of_origin: '',
          tissue_type: 'TumorTissue',
          to_trim_adapter_sequence: '',
          tobacco_smoking_onset_year: '',
          tobacco_smoking_quit_year: '',
          tobacco_smoking_status: '',
          tobacco_use_per_day: '',
          transcript: '',
          transglottic_extension: '',
          treatment__submitter_id: '',
          treatment_anatomic_site: '',
          treatment_arm: '',
          treatment_dose: '',
          treatment_dose_units: '',
          treatment_effect: '',
          treatment_effect_indicator: '',
          treatment_frequency: '',
          treatment_intent_type: '',
          treatment_or_therapy: '',
          treatment_outcome: '',
          treatment_type: '',
          tumor_code: '',
          tumor_code_id: '',
          tumor_confined_to_organ_of_origin: '',
          tumor_depth: '',
          tumor_descriptor: '',
          tumor_focality: '',
          tumor_grade: 'NA',
          tumor_largest_dimension_diameter: '4',
          tumor_regression_grade: '',
          tumor_stage: '',
          type_of_smoke_exposure: '',
          type_of_tobacco_used: '',
          variant_origin: '',
          variant_type: '',
          vascular_invasion_present: '',
          vascular_invasion_type: '',
          viral_hepatitis_serologies: '',
          vital_status: '',
          weeks_gestation_at_birth: '',
          weiss_assessment_score: '',
          well_number: '',
          who_cns_grade: '',
          who_nte_grade: '',
          wilms_tumor_histologic_subtype: '',
          year_of_birth: '',
          year_of_death: '',
          year_of_diagnosis: '',
          years_smoked: '',
          zygosity: ''
        }
      ],
      columns,
      innerColumns,
      innerData: [
        {
          modelName: 'PIK3CA_Mutation',
          description: 'PIK3CA Mutation Model',
          status: 'Success'
        },
        {
          modelName: 'BLIS',
          description: 'Basal-like Immunosuppressed Model',
          status: 'Success'
        },
        {
          modelName: 'IM',
          description: 'Immunomodulatory Model',
          status: 'Success'
        },
        {
          modelName: 'LAR',
          description: 'Luminal Androgen Receptor (LAR) Model',
          status: 'Success'
        },
        {
          modelName: 'MES',
          description: 'Mesenchymal (MES) Model',
          status: 'Success'
        }
      ],
      modelOptions: [
        { label: 'PIK3CA Mutation Model', value: 'PIK3CA_Mutation' },
        { label: 'Basal-like Immunosuppressed Model', value: 'BLIS' },
        { label: 'Immunomodulatory Model', value: 'IM' },
        { label: 'Luminal Androgen Receptor (LAR) Model', value: 'LAR' },
        { label: 'Mesenchymal (MES) Model', value: 'MES' }
      ],
      visible: false
    }
  },
  methods: {
    redirectToRecord(recordId, project) {
      this.$router.push({
        name: 'record-viewer',
        query: {
          recordId: recordId,
          project: project
        }
      })
    },
    showModal() {
      this.visible = true
    },
    hideModal() {
      this.visible = false
    },
    prediction(models) {}
  }
}
</script>

<style lang="less">
.pathology-model-container {
  width: 100%;
  height: 100%;
  background-color: #fff;

  .ant-pagination {
    margin-right: 5px;
  }

  .inner-table {
    margin: 0px !important;
    border-radius: 5px;
    border: 1px solid #d6d6d6;
  }
}

.prediction-modal {
  .ant-modal-body {
    padding: 16px 24px;
  }
}
</style>
